print("This project is used for creating wen app for Video translation")
print("Sceond time -commit")
print("Third time -commit")
print("fourth time -commit")
print("fifth time -commit")
print("sixth time -commit")
print("7th time -commit")
print("8th time -commit")
print("9th time -commit")
print("10th time -commit")